M48
; DRILL file {KiCad (6.0.0)} date Tue May 24 21:35:41 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-24T21:35:41-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X59.436Y-39.624
X59.436Y-163.068
X163.576Y-39.624
X163.576Y-163.068
T0
M30
